[package]
name = "vrc-avpro-sucks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
lazy-regex = "3.1.0"
notify = "6.1.1"
regex = "1.10.3"
signal-hook = "0.3.17"
